const assert=require('node:assert/strict');
const {createServer}=require('./server.cjs');
const {closeServer,launchBrowser,listen,makeWav}=require('./test-helpers.cjs');

(async()=>{
  const server=createServer(),base=await listen(server);let browser;
  try{
    browser=await launchBrowser();const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(base+'/index.html');
    await page.locator('#tourButton').click();assert(await page.locator('#welcomeDialog').evaluate(dialog=>dialog.open));await page.locator('#tourClose').click();assert(!await page.locator('#welcomeDialog').evaluate(dialog=>dialog.open));
    await page.locator('#f').setInputFiles({name:'Test Artist - Player Song.wav',mimeType:'audio/wav',buffer:makeWav({seconds:2})});await page.waitForFunction(()=>document.querySelector('#playerState').dataset.state==='ready');
    const metadata=await page.evaluate(()=>({title:$('trackTitle').textContent,artist:$('trackArtist').textContent,source:$('trackSource').textContent,details:$('trackDetails').textContent,art:$('albumArt').style.backgroundImage,mini:!$('miniPlayer').hidden}));
    assert.equal(metadata.title,'Player Song');assert.equal(metadata.artist,'Test Artist');assert.equal(metadata.source,'Local file');assert(metadata.details.includes('2ch')&&metadata.art&&metadata.mini,'complete now-playing metadata');assert.equal(await page.locator('#qualityState').innerText(),'Clarity');await page.locator('#qualityState').click();assert.equal(await page.locator('#renderMode').inputValue(),'room');await page.locator('#qualityState').click();assert.equal(await page.locator('#renderMode').inputValue(),'immersive');await page.locator('#qualityState').click();assert.equal(await page.locator('#renderMode').inputValue(),'clarity');assert.equal(await page.locator('#walls').isChecked(),false);
    await page.locator('#play').click();await page.waitForFunction(()=>document.querySelector('#playerState').dataset.state==='playing'&&+document.querySelector('#seek').value>0);assert.equal(await page.locator('#play').innerText(),'Pause');assert.match(await page.locator('#time').innerText(),/^0:0\d \/ 0:0[12]$/);
    await page.locator('#tab-source').click();assert.equal(await page.locator('#miniPlayer').evaluate(element=>getComputedStyle(element).display),'grid');assert.equal(await page.locator('#miniTitle').innerText(),'Player Song');await page.locator('#miniPlay').click();assert.equal(await page.locator('#playerState').getAttribute('data-state'),'paused');
    await page.locator('#tab-stage').click();await page.locator('#mute').click();assert.equal(await page.locator('#mvol').inputValue(),'0');assert.equal(await page.locator('#mute').getAttribute('aria-pressed'),'true');await page.locator('#mute').click();assert.notEqual(await page.locator('#mvol').inputValue(),'0');await page.locator('#repeat').click();assert.equal(await page.locator('#repeat').getAttribute('aria-pressed'),'false');await page.locator('#stop').click();assert.equal(await page.locator('#seek').inputValue(),'0');
    await page.locator('#tab-room').click();const furnitureGroup=page.locator('details.group:has(#addBed)');if(!await furnitureGroup.evaluate(element=>element.open))await furnitureGroup.locator('summary').click();await page.locator('#addBed').click();assert.equal(await page.evaluate(()=>furniture.length),1);
    await page.locator('#tab-rig').click();const projectGroup=page.locator('details.group:has(#saveProject)');if(!await projectGroup.evaluate(element=>element.open))await projectGroup.locator('summary').click();await page.locator('#saveSlotA').click();assert.equal(await page.locator('#loadSlotA').isDisabled(),false);await page.locator('#resetProject').click();assert.equal(await page.evaluate(()=>furniture.length),0);await page.locator('#loadSlotA').click();assert.equal(await page.evaluate(()=>furniture.length),1);await page.locator('#saveProject').click();await page.locator('#resetProject').click();assert.equal(await page.evaluate(()=>furniture.length),0);await page.locator('#restoreProject').click();assert.equal(await page.evaluate(()=>furniture.length),1);assert.match(await page.locator('#projectStatus').innerText(),/restored/i);
    await page.locator('#tab-stage').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#tab-source').getAttribute('aria-selected'),'true');assert.equal(await page.locator('#tab-source').getAttribute('aria-controls'),'panel-source');
    const retinaContext=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:2});const retina=await retinaContext.newPage();await retina.goto(base+'/index.html');assert.deepEqual(await retina.evaluate(()=>{draw();return {display:[c.width,c.height],logical:[CANVAS_WIDTH,CANVAS_HEIGHT],scale:CANVAS_SCALE,transform:x2.getTransform().a};}),{display:[1800,1200],logical:[900,600],scale:2,transform:2},'large HiDPI canvas renders natively at 2x');await retinaContext.close();const phoneContext=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true});const phone=await phoneContext.newPage();await phone.goto(base+'/index.html');assert.deepEqual(await phone.evaluate(()=>({display:[c.width,c.height],scale:CANVAS_SCALE})),{display:[900,600],scale:1},'a phone-sized stage is already near native at 1x');await phoneContext.close();
    assert.deepEqual(errors,[],'no player/project page errors');console.log('PASS: tour, local track player, mini transport, project/A-B restore, keyboard tabs, and HiDPI stage work.');
  }finally{if(browser)await browser.close();await closeServer(server);}
})().catch(error=>{console.error(error);process.exitCode=1;});
